{ ... }: {
  imports = [
    ./_1password/home.nix
    ./alacritty/home.nix
    ./alacritty/linux.nix
    ./battery-notifications/home.nix
    ./direnv/home.nix
    ./encode_queue/home.nix
    ./firefox/home.nix
    ./fish/home.nix
    ./fuzzel/home.nix
    ./gh/home.nix
    ./git/home.nix
    ./helix/home.nix
    ./hyprlax/home.nix
    ./jellybox/home.nix
    ./keybase/home.nix
    ./lazygit/home.nix
    ./mako/home.nix
    ./niri/home.nix
    ./obs-studio/home.nix
    ./paseo-desktop/home.nix
    ./polkit-kde/home.nix
    ./steambox/home.nix
    ./swaybg/home.nix
    ./swayidle/home.nix
    ./swaylock/home.nix
    ./unfree/home.nix
  ];
}
