# CREATING A USER KEY
#
# mkdir -p ~/.config/sops/age
# nix shell nixpkgs#age -c age-keygen -o ~/.config/sops/age/keys.txt
# chmod 600 ~/.config/sops/age/keys.txt
#
#
# GETTING A HOST KEY
#
# sudo nix shell nixpkgs#ssh-to-age -c sh -c 'ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub'
keys:
  - &waktu_redtruck age1rd9d5xr3v4adrec0umhvwvrcgxgy3qylzg3ngcqr8cnjpy5faafsl3u7fs
  - &waktu_t495 age19unwz2yux3uew0gqcrrfnqxr0kcr5xj7au2e9n75y8d3cj0gp58sqz6305

  - &host_redtruck age16a96arz6f3jnetmeq77q6vcfwdylj59hekg7v09eyfsrtamlc9vqudj8dd
  - &host_t495 age1rym6aylq50jucfelkgj28a8j27ag6ajzeazysxyls5n3pvsa5vssuvc9wq
  - &host_paynefield age1anxkzm9fplrrdcn5gpdjp0qz0lg4uawzudlps80veueeptwmk4ms6seu7j
  - &host_vps age1e2uwgdjehu3xh0pk57hsnlz98rzntpfakaw5qvav9hl6u2vqza9sll5qz7

creation_rules:
  - path_regex: secrets/users/waktu\.yaml$
    key_groups:
      - age:
          - *waktu_redtruck
          - *waktu_t495
          - *host_redtruck
          - *host_t495
          - *host_paynefield
          - *host_vps

  - path_regex: secrets/users/sumriri\.yaml$
    key_groups:
      - age:
          - *waktu_redtruck
          - *waktu_t495
          - *host_t495

  - path_regex: secrets/users/link\.yaml$
    key_groups:
      - age:
          - *waktu_redtruck
          - *waktu_t495
          - *host_t495

  - path_regex: secrets/hosts/redtruck\.yaml$
    key_groups:
      - age:
          - *waktu_redtruck
          - *waktu_t495
          - *host_redtruck

  - path_regex: secrets/hosts/t495\.yaml$
    key_groups:
      - age:
          - *waktu_redtruck
          - *waktu_t495
          - *host_t495

  - path_regex: secrets/hosts/paynefield\.yaml$
    key_groups:
      - age:
          - *waktu_redtruck
          - *waktu_t495
          - *host_paynefield

  - path_regex: secrets/hosts/vps\.yaml$
    key_groups:
      - age:
          - *waktu_redtruck
          - *waktu_t495
          - *host_vps

  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *waktu_redtruck
          - *waktu_t495
