{
  nixpkgs,
  inputs,
  pkgs,
}:
let
  # Generated from nixosConfigurations/darwinConfigurations rather than
  # listed, so a host added later is checked automatically.
  evalOnly = name: drvPath: builtins.seq drvPath (pkgs.runCommand "eval-${name}" { } "touch $out");
  evalAll =
    prefix:
    nixpkgs.lib.mapAttrs' (
      name: cfg:
      let
        checkName = "${prefix}-${name}";
      in
      nixpkgs.lib.nameValuePair checkName (evalOnly checkName cfg.config.system.build.toplevel.drvPath)
    );
  lintSrc = pkgs.lib.cleanSource ../.;
  # Generated by nixos-generate-config; its first line says not to
  # edit it. statix needs no such exclusion - see statix.toml.
  hwConfigGlob = "hosts/*/hardware-configuration.nix";
in
evalAll "nixos" inputs.self.nixosConfigurations
// evalAll "darwin" inputs.self.darwinConfigurations
// {
  devboxes = import ../tests/devboxes.nix {
    inherit nixpkgs inputs;
    system = "x86_64-linux";
  };
  photoform = import ../tests/photoform.nix {
    inherit nixpkgs inputs;
    system = "x86_64-linux";
  };
  # The throwaway git repo is load-bearing twice over: treefmt bounds
  # its walk to a VCS root, and walks via git. Without `init` it walks
  # to /; without `-Af` it skips gitignored files and the check passes
  # on an unformatted one.
  fmt-check =
    pkgs.runCommand "fmt-check"
      {
        nativeBuildInputs = [
          inputs.self.formatter.x86_64-linux
          pkgs.git
        ];
      }
      ''
        cp -r --no-preserve=mode ${lintSrc} src
        cd src
        git init -q
        git add -Af
        treefmt --fail-on-change --no-cache
        touch $out
      '';
  statix-check =
    pkgs.runCommand "statix-check"
      {
        nativeBuildInputs = [ pkgs.statix ];
      }
      ''
        cd ${lintSrc}
        statix check .
        touch $out
      '';
  deadnix-check =
    pkgs.runCommand "deadnix-check"
      {
        nativeBuildInputs = [ pkgs.deadnix ];
      }
      ''
        cd ${lintSrc}
        deadnix --fail . --exclude ${hwConfigGlob}
        touch $out
      '';
}
# `nix flake check` skips a check whose output a substituter already has, so
# an unchanged package costs nothing here once CI reads from the cache.
# Only flake `packages` are covered: a derivation defined inside a module
# (a callPackage that never becomes a flake output) is structurally outside
# this set and stays unchecked.
// nixpkgs.lib.mapAttrs' (
  name: drv: nixpkgs.lib.nameValuePair "pkg-${name}" drv
) inputs.self.packages.x86_64-linux
# Adapts every caddy host's real Caddyfile so a layer4 syntax error is a CI
# failure instead of surfacing first on deploy.
//
  nixpkgs.lib.mapAttrs'
    (
      name: cfg:
      nixpkgs.lib.nameValuePair "caddyfile-${name}" (
        pkgs.runCommand "caddyfile-${name}"
          {
            nativeBuildInputs = [ cfg.config.services.caddy.package ];
          }
          ''
            HOME=$TMPDIR caddy adapt \
              --config ${cfg.config.services.caddy.configFile} \
              --adapter caddyfile > $out
          ''
      )
    )
    (nixpkgs.lib.filterAttrs (_: cfg: cfg.config.services.caddy.enable) inputs.self.nixosConfigurations)
